/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ianre
 */
public class pantallaDeBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form pantallaDeBienvenida
     */
    public pantallaDeBienvenida() {
        initComponents();
        this.setLocationRelativeTo(null); // Interfaz centrada
        // Cargar el archivo de icono
        ImageIcon icono = new ImageIcon("C:/Users/ianre/Web/Trivia/resources/icono.png");
        // Asignar el icono a la ventana principal
        setIconImage(icono.getImage());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mensajeBienvenida = new javax.swing.JLabel();
        botonComenzar = new javax.swing.JButton();
        mensajeBienvenida2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mensajeBienvenida.setText("¡Bienvenid@ a [nombre Trivia]!");
        jPanel1.add(mensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        botonComenzar.setBackground(new java.awt.Color(255, 255, 255));
        botonComenzar.setText("Comenzar");
        jPanel1.add(botonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        mensajeBienvenida2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensajeBienvenida2.setText("Descubre cuánto sabes...");
        jPanel1.add(mensajeBienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaDeBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComenzar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajeBienvenida;
    private javax.swing.JLabel mensajeBienvenida2;
    // End of variables declaration//GEN-END:variables
}
