/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showOptionDialog;
import javax.sound.sampled.*;

/**
 *
 * @author ianre
 */
public class pantallaDeBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form pantallaDeBienvenida
     */
    public pantallaDeBienvenida() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null); // Interfaz centrada
        // Cargar el archivo de icono
        ImageIcon icono = new ImageIcon("C:/Users/ianre/Web/Trivia/resources/icono.png");
        // Asignar el icono a la ventana principal
        setIconImage(icono.getImage());
    
        ReproducirSonido("cancion.wav");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mensajeBienvenida = new javax.swing.JLabel();
        botonComenzar = new javax.swing.JButton();
        mensajeBienvenida2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensajeBienvenida.setBackground(new java.awt.Color(0, 0, 0));
        mensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mensajeBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        mensajeBienvenida.setText("Bienvenid@ a SudoTrivia");
        jPanel1.add(mensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        botonComenzar.setBackground(new java.awt.Color(255, 255, 255));
        botonComenzar.setText("Comenzar");
        botonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(botonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        mensajeBienvenida2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensajeBienvenida2.setForeground(new java.awt.Color(0, 0, 51));
        mensajeBienvenida2.setText("¡Suspende ya, en la semana post-examenes!");
        jPanel1.add(mensajeBienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ianre\\Web\\Trivia\\resources\\perroRana2.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 110, 110));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ianre\\Web\\Trivia\\resources\\bukoni.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 90, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ianre\\Web\\Trivia\\resources\\pregunta.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 110, 110));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ianre\\Web\\Trivia\\resources\\bailando.gif")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 80, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComenzarActionPerformed
        // Comenzar el juego (cambiar a pantalla rondaDePreguntas):
    
        rondaDePreguntas ventana = new rondaDePreguntas();
        String[] opciones = {"Siempre", "No :("};
        ImageIcon icono = new ImageIcon("C:/Users/ianre/Web/Trivia/resources/hasbullaA.png");
        int respuesta = showOptionDialog(null, "Tienes un minuto para responder 4 preguntas, haz click en siguiente cuando termines con una ronda ¿Estás listo?", "Comenzar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icono, opciones, opciones[0]);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.out.println("Comenzando el juego...");
            this.setVisible(false);
            ventana.setVisible(true);
        } else {
            System.out.println("Esperamos :)");
        }
        
    }//GEN-LAST:event_botonComenzarActionPerformed

    public void ReproducirSonido(String nombreSonido) throws IOException{
       try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(nombreSonido).getAbsoluteFile());
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
       } catch(UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
         System.out.println("Error al reproducir el sonido.");
       }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaDeBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pantallaDeBienvenida().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(pantallaDeBienvenida.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComenzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajeBienvenida;
    private javax.swing.JLabel mensajeBienvenida2;
    // End of variables declaration//GEN-END:variables
}
