/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import trivia.Pregunta;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author ianre
 */
public class rondaDePreguntas extends javax.swing.JFrame {

    /**
     * Creates new form rondaDePreguntas
     */
    
    ArrayList<String> preguntas = new ArrayList<>();
    ArrayList<String> respuestas1 = new ArrayList<>();
    ArrayList<String> respuestas2 = new ArrayList<>();
    ArrayList<String> respuestas3 = new ArrayList<>();
    ArrayList<String> respuestas4 = new ArrayList<>();
    private int indiceRespuestas1;
    private int indiceRespuestas2;
    private int indiceRespuestas3;
    private int indiceRespuestas4;
    private int indiceRespuestas5;
    private int indiceRespuestas6;
    private int indiceRespuestas7;
    private int indiceRespuestas8;
    private int indiceRespuestas9;
    private int indiceRespuestas10;
    private int indiceRespuestas11;
    private int indiceRespuestas12;
    int indice = 0;
    int puntuacion = 0;
    private ScheduledExecutorService executor;
    private int tiempoRestante;
    boolean estado = false;
    private int numeroRonda = 1;
    private boolean ventanaAbierta = true;
    
    public rondaDePreguntas() {
        initComponents();
        this.setLocationRelativeTo(null); // Interfaz centrada
        // Cargar el archivo de icono
        ImageIcon icono = new ImageIcon("C:/Users/ianre/Web/Trivia/resources/icono.png");
        // Asignar el icono a la ventana principal
        setIconImage(icono.getImage());
        // Crear pregunta 1 de ronda 1
        CrearPregunta1();
        
        finDeJuego ventanaFinJuego = new finDeJuego(puntuacion);
        ventanaFinJuego.setVisible(false);
        
        iniciarTemporizador();
        
        
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoResp = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fondoPreg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        fondoResp.setBackground(new java.awt.Color(95, 158, 160));
        fondoResp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OPCION");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 60));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("OPCION");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, 60));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OPCION");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, 60));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("OPCION");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 130, 60));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("OPCION");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 60));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("OPCION");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 60));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setText("OPCION");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 130, 60));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("OPCION");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 130, 60));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setText("OPCION");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 60));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setText("OPCION");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 130, 60));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setText("OPCION");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 130, 60));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setText("OPCION");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        fondoResp.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 130, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SUDOTRIVIA");
        fondoResp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 130, 20));

        fondoPreg.setBackground(new java.awt.Color(18, 46, 73));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿[PREGUNTA]?");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("Siguiente");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tiempo:");

        javax.swing.GroupLayout fondoPregLayout = new javax.swing.GroupLayout(fondoPreg);
        fondoPreg.setLayout(fondoPregLayout);
        fondoPregLayout.setHorizontalGroup(
            fondoPregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoPregLayout.createSequentialGroup()
                .addGroup(fondoPregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoPregLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton13))
                    .addGroup(fondoPregLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoPregLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(52, 52, 52))
        );
        fondoPregLayout.setVerticalGroup(
            fondoPregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPregLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoPregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoPreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoPreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarTemporizador() {
        tiempoRestante = 121; // Tiempo en segundos

        executor = Executors.newSingleThreadScheduledExecutor();
        executor.scheduleAtFixedRate(new Runnable() {
            
            public void run() {
                // Tu código de contador aquí
                while (ventanaAbierta && tiempoRestante >= 0) {
                    tiempoRestante--;
                    if (tiempoRestante >= 0) {
                        jLabel2.setText(String.valueOf(tiempoRestante));
                    } else if (tiempoRestante <= 0){
                        executor.shutdown(); // Detener el temporizador
                        JOptionPane.showMessageDialog(null, "¡Se acabó el tiempo!");
                        jButton1.setEnabled(false);
                        jButton2.setEnabled(false);
                        jButton3.setEnabled(false);
                        jButton4.setEnabled(false);
                        jButton5.setEnabled(false);
                        jButton6.setEnabled(false);
                        jButton7.setEnabled(false);
                        jButton8.setEnabled(false);
                        jButton9.setEnabled(false);
                        jButton10.setEnabled(false);
                        jButton11.setEnabled(false);
                        jButton12.setEnabled(false);
                        jLabel3.setText("");
                    }

                    // Verificar si la ventana se cerró
                    if (!ventanaAbierta) {
                        executor.shutdown(); // Detener el temporizador si la ventana se cerró
                        break; // Salir del bucle si la ventana se cerró
                    }

                    try {
                        Thread.sleep(1000); // Esperar 1 segundo
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }, 1, 1, TimeUnit.SECONDS);
        
    } 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        System.out.println(indiceRespuestas1);
        if (indiceRespuestas1 <= 5) {
            // Cambiar el color del botón a verde
            jButton1.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas1 > 5) {
            jButton1.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas2);

        if (indiceRespuestas2 <= 5) {
            // Cambiar el color del botón a verde
            jButton2.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas2 > 5) {
            jButton2.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas3);

        if (indiceRespuestas3 <= 5) {
            // Cambiar el color del botón a verde
            jButton3.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas3 > 5) {
            jButton3.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas4);

        if (indiceRespuestas4 <= 5) {
            // Cambiar el color del botón a verde
            jButton4.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas4 > 5) {
            jButton4.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas5);

        if (indiceRespuestas5 <= 5) {
            // Cambiar el color del botón a verde
            jButton5.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas5 > 5) {
            jButton5.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
       System.out.println(indiceRespuestas6);

        if (indiceRespuestas6 <= 5) {
            // Cambiar el color del botón a verde
            jButton6.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas6 > 5) {
            jButton6.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas7);
        
        if (indiceRespuestas7 <= 5) {
            // Cambiar el color del botón a verde
            jButton7.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas7 > 5) {
            jButton7.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas8);
       
        if (indiceRespuestas8 <= 5) {
            // Cambiar el color del botón a verde
            jButton8.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas8 > 5) {
            jButton8.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas9);

        if (indiceRespuestas9 <= 5) {
            // Cambiar el color del botón a verde
            jButton9.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas9 > 5) {
            jButton9.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas10);

        if (indiceRespuestas10 <= 5) {
            // Cambiar el color del botón a verde
            jButton10.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas10 > 5) {
            jButton10.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas11);

        if (indiceRespuestas11 <= 5) {
            // Cambiar el color del botón a verde
            jButton11.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas11 > 5) {
            jButton11.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Lógica para verificar si la opción seleccionada es correcta o incorrecta.
        // Respuesta seleccionada:
        System.out.println(indiceRespuestas12);

        if (indiceRespuestas12 <= 5) {
            // Cambiar el color del botón a verde
            jButton12.setBackground(new java.awt.Color(124,252,0));
            puntuacion++;
            System.out.println(puntuacion);
        } else if (indiceRespuestas12 > 5) {
            jButton12.setBackground(new java.awt.Color(255,160,122));
            puntuacion--;
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int numeroMaxRondas = 4;

        if (numeroRonda >= numeroMaxRondas) {
            this.dispose(); // Cierra la ventana
            
            finDeJuego ventanaFinJuego = new finDeJuego(puntuacion);
            ventanaFinJuego.setVisible(true);
            System.out.println(estado);
        } else if (numeroRonda == 1) {
            CrearPregunta2();
            jButton1.setBackground(new java.awt.Color(255,255,255));
            jButton2.setBackground(new java.awt.Color(255,255,255));
            jButton3.setBackground(new java.awt.Color(255,255,255));
            jButton4.setBackground(new java.awt.Color(255,255,255));
            jButton5.setBackground(new java.awt.Color(255,255,255));
            jButton6.setBackground(new java.awt.Color(255,255,255));
            jButton7.setBackground(new java.awt.Color(255,255,255));
            jButton8.setBackground(new java.awt.Color(255,255,255));
            jButton9.setBackground(new java.awt.Color(255,255,255));
            jButton10.setBackground(new java.awt.Color(255,255,255));
            jButton11.setBackground(new java.awt.Color(255,255,255));
            jButton12.setBackground(new java.awt.Color(255,255,255));
            numeroRonda++; // Incrementar el contador después de ejecutar CrearPregunta2()
        } else if (numeroRonda == 2) {
            CrearPregunta3();
            jButton1.setBackground(new java.awt.Color(255,255,255));
            jButton2.setBackground(new java.awt.Color(255,255,255));
            jButton3.setBackground(new java.awt.Color(255,255,255));
            jButton4.setBackground(new java.awt.Color(255,255,255));
            jButton5.setBackground(new java.awt.Color(255,255,255));
            jButton6.setBackground(new java.awt.Color(255,255,255));
            jButton7.setBackground(new java.awt.Color(255,255,255));
            jButton8.setBackground(new java.awt.Color(255,255,255));
            jButton9.setBackground(new java.awt.Color(255,255,255));
            jButton10.setBackground(new java.awt.Color(255,255,255));
            jButton11.setBackground(new java.awt.Color(255,255,255));
            jButton12.setBackground(new java.awt.Color(255,255,255));
            numeroRonda++; // Incrementar el contador después de ejecutar CrearPregunta3()
        } else if (numeroRonda == 3) {
            CrearPregunta4();
            jButton1.setBackground(new java.awt.Color(255,255,255));
            jButton2.setBackground(new java.awt.Color(255,255,255));
            jButton3.setBackground(new java.awt.Color(255,255,255));
            jButton4.setBackground(new java.awt.Color(255,255,255));
            jButton5.setBackground(new java.awt.Color(255,255,255));
            jButton6.setBackground(new java.awt.Color(255,255,255));
            jButton7.setBackground(new java.awt.Color(255,255,255));
            jButton8.setBackground(new java.awt.Color(255,255,255));
            jButton9.setBackground(new java.awt.Color(255,255,255));
            jButton10.setBackground(new java.awt.Color(255,255,255));
            jButton11.setBackground(new java.awt.Color(255,255,255));
            jButton12.setBackground(new java.awt.Color(255,255,255));
            numeroRonda++; // Incrementar el contador después de ejecutar CrearPregunta4()
        }

        System.out.println(numeroRonda);
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseEntered
    
    private void CrearPregunta1() { // como parametro puede ponerse la ronda (la pregunta)
        // Instanciamos la clase Pregunta
        Pregunta pregunta = new Pregunta(preguntas, respuestas1);
        pregunta.AñadeDatos();
        preguntas = pregunta.getPreguntas();
        respuestas1 = pregunta.getRespuestas1();
        
        // Obtener un índice aleatorio
        Random random = new Random();
        indice = random.nextInt(preguntas.size());
        System.out.println(indice * 3);
        System.out.println(indice * 3 + 1);
        
        // Insertamos en los elementos de nuestra ventana
        jLabel1.setText(preguntas.get(0)); // Establece la primera pregunta en un JLabel
        jButton1.setText(respuestas1.get(indice * 3)); // Establece la respuesta de la primera pregunta en un JButton
        jButton2.setText(respuestas1.get(indice * 3 + 1)); 
        jButton3.setText(respuestas1.get(indice * 3 + 2)); 
        jButton4.setText(respuestas1.get(indice * 3 + 3)); 
        jButton5.setText(respuestas1.get(indice * 3 + 4)); 
        jButton6.setText(respuestas1.get(indice * 3 + 5)); 
        jButton7.setText(respuestas1.get(indice * 3 + 6)); 
        jButton8.setText(respuestas1.get(indice * 3 + 7)); 
        jButton9.setText(respuestas1.get(indice * 3 + 8)); 
        jButton10.setText(respuestas1.get(indice * 3 + 9));
        jButton11.setText(respuestas1.get(indice * 3 + 10));
        jButton12.setText(respuestas1.get(indice * 3 + 11));
        indiceRespuestas1 = respuestas1.indexOf(respuestas1.get(indice * 3));
        indiceRespuestas2 = respuestas1.indexOf(respuestas1.get(indice * 3+1));
        indiceRespuestas3 = respuestas1.indexOf(respuestas1.get(indice * 3+2));
        indiceRespuestas4 = respuestas1.indexOf(respuestas1.get(indice * 3+3));
        indiceRespuestas5 = respuestas1.indexOf(respuestas1.get(indice * 3+4));
        indiceRespuestas6 = respuestas1.indexOf(respuestas1.get(indice * 3+5));
        indiceRespuestas7 = respuestas1.indexOf(respuestas1.get(indice * 3+6));
        indiceRespuestas8 = respuestas1.indexOf(respuestas1.get(indice * 3+7));
        indiceRespuestas9 = respuestas1.indexOf(respuestas1.get(indice * 3+8));
        indiceRespuestas10 = respuestas1.indexOf(respuestas1.get(indice * 3+9));
        indiceRespuestas11 = respuestas1.indexOf(respuestas1.get(indice * 3+10));
        indiceRespuestas12 = respuestas1.indexOf(respuestas1.get(indice * 3+11));
    }
    
    private void CrearPregunta2() { // como parametro puede ponerse la ronda (la pregunta)
        // Instanciamos la clase Pregunta
        Pregunta pregunta = new Pregunta(preguntas, respuestas1);
        pregunta.AñadeDatos();
        preguntas = pregunta.getPreguntas();
        respuestas2 = pregunta.getRespuestas2();
        
        // Obtener un índice aleatorio
        Random random = new Random();
        indice = random.nextInt(preguntas.size());
        System.out.println(indice * 3);
        System.out.println(indice * 3 + 1);
        
        // Insertamos en los elementos de nuestra ventana
        jLabel1.setText(preguntas.get(1)); // Establece la primera pregunta en un JLabel
        jButton1.setText(respuestas2.get(indice * 3)); // Establece la respuesta de la primera pregunta en un JButton
        jButton2.setText(respuestas2.get(indice * 3 + 1)); 
        jButton3.setText(respuestas2.get(indice * 3 + 2)); 
        jButton4.setText(respuestas2.get(indice * 3 + 3)); 
        jButton5.setText(respuestas2.get(indice * 3 + 4)); 
        jButton6.setText(respuestas2.get(indice * 3 + 5)); 
        jButton7.setText(respuestas2.get(indice * 3 + 6)); 
        jButton8.setText(respuestas2.get(indice * 3 + 7)); 
        jButton9.setText(respuestas2.get(indice * 3 + 8)); 
        jButton10.setText(respuestas2.get(indice * 3 + 9));
        jButton11.setText(respuestas2.get(indice * 3 + 10));
        jButton12.setText(respuestas2.get(indice * 3 + 11));
        indiceRespuestas1 = respuestas2.indexOf(respuestas2.get(indice * 3));
        indiceRespuestas2 = respuestas2.indexOf(respuestas2.get(indice * 3+1));
        indiceRespuestas3 = respuestas2.indexOf(respuestas2.get(indice * 3+2));
        indiceRespuestas4 = respuestas2.indexOf(respuestas2.get(indice * 3+3));
        indiceRespuestas5 = respuestas2.indexOf(respuestas2.get(indice * 3+4));
        indiceRespuestas6 = respuestas2.indexOf(respuestas2.get(indice * 3+5));
        indiceRespuestas7 = respuestas2.indexOf(respuestas2.get(indice * 3+6));
        indiceRespuestas8 = respuestas2.indexOf(respuestas2.get(indice * 3+7));
        indiceRespuestas9 = respuestas2.indexOf(respuestas2.get(indice * 3+8));
        indiceRespuestas10 = respuestas2.indexOf(respuestas2.get(indice * 3+9));
        indiceRespuestas11 = respuestas2.indexOf(respuestas2.get(indice * 3+10));
        indiceRespuestas12 = respuestas2.indexOf(respuestas2.get(indice * 3+11));
    }
    
    private void CrearPregunta3() { // como parametro puede ponerse la ronda (la pregunta)
        // Instanciamos la clase Pregunta
        Pregunta pregunta = new Pregunta(preguntas, respuestas1);
        pregunta.AñadeDatos();
        preguntas = pregunta.getPreguntas();
        respuestas3 = pregunta.getRespuestas3();
        
        // Obtener un índice aleatorio
        Random random = new Random();
        indice = random.nextInt(preguntas.size());
        System.out.println(indice * 3);
        System.out.println(indice * 3 + 1);
        
        // Insertamos en los elementos de nuestra ventana
        jLabel1.setText(preguntas.get(2)); // Establece la primera pregunta en un JLabel
        jButton1.setText(respuestas3.get(indice * 3)); // Establece la respuesta de la primera pregunta en un JButton
        jButton2.setText(respuestas3.get(indice * 3 + 1)); 
        jButton3.setText(respuestas3.get(indice * 3 + 2)); 
        jButton4.setText(respuestas3.get(indice * 3 + 3)); 
        jButton5.setText(respuestas3.get(indice * 3 + 4)); 
        jButton6.setText(respuestas3.get(indice * 3 + 5)); 
        jButton7.setText(respuestas3.get(indice * 3 + 6)); 
        jButton8.setText(respuestas3.get(indice * 3 + 7)); 
        jButton9.setText(respuestas3.get(indice * 3 + 8)); 
        jButton10.setText(respuestas3.get(indice * 3 + 9));
        jButton11.setText(respuestas3.get(indice * 3 + 10));
        jButton12.setText(respuestas3.get(indice * 3 + 11));
        indiceRespuestas1 = respuestas3.indexOf(respuestas3.get(indice * 3));
        indiceRespuestas2 = respuestas3.indexOf(respuestas3.get(indice * 3+1));
        indiceRespuestas3 = respuestas3.indexOf(respuestas3.get(indice * 3+2));
        indiceRespuestas4 = respuestas3.indexOf(respuestas3.get(indice * 3+3));
        indiceRespuestas5 = respuestas3.indexOf(respuestas3.get(indice * 3+4));
        indiceRespuestas6 = respuestas3.indexOf(respuestas3.get(indice * 3+5));
        indiceRespuestas7 = respuestas3.indexOf(respuestas3.get(indice * 3+6));
        indiceRespuestas8 = respuestas3.indexOf(respuestas3.get(indice * 3+7));
        indiceRespuestas9 = respuestas3.indexOf(respuestas3.get(indice * 3+8));
        indiceRespuestas10 = respuestas3.indexOf(respuestas3.get(indice * 3+9));
        indiceRespuestas11 = respuestas3.indexOf(respuestas3.get(indice * 3+10));
        indiceRespuestas12 = respuestas3.indexOf(respuestas3.get(indice * 3+11));
    }
    private void CrearPregunta4() { // como parametro puede ponerse la ronda (la pregunta)
        // Instanciamos la clase Pregunta
        Pregunta pregunta = new Pregunta(preguntas, respuestas1);
        pregunta.AñadeDatos();
        preguntas = pregunta.getPreguntas();
        respuestas4 = pregunta.getRespuestas4();
        
        // Obtener un índice aleatorio
        Random random = new Random();
        indice = random.nextInt(preguntas.size());
        System.out.println(indice * 3);
        System.out.println(indice * 3 + 1);
        
        // Insertamos en los elementos de nuestra ventana
        jLabel1.setText(preguntas.get(3)); // Establece la primera pregunta en un JLabel
        jButton1.setText(respuestas4.get(indice * 3)); // Establece la respuesta de la primera pregunta en un JButton
        jButton2.setText(respuestas4.get(indice * 3 + 1)); 
        jButton3.setText(respuestas4.get(indice * 3 + 2)); 
        jButton4.setText(respuestas4.get(indice * 3 + 3)); 
        jButton5.setText(respuestas4.get(indice * 3 + 4)); 
        jButton6.setText(respuestas4.get(indice * 3 + 5)); 
        jButton7.setText(respuestas4.get(indice * 3 + 6)); 
        jButton8.setText(respuestas4.get(indice * 3 + 7)); 
        jButton9.setText(respuestas4.get(indice * 3 + 8)); 
        jButton10.setText(respuestas4.get(indice * 3 + 9));
        jButton11.setText(respuestas4.get(indice * 3 + 10));
        jButton12.setText(respuestas4.get(indice * 3 + 11));
        indiceRespuestas1 = respuestas4.indexOf(respuestas4.get(indice * 3));
        indiceRespuestas2 = respuestas4.indexOf(respuestas4.get(indice * 3+1));
        indiceRespuestas3 = respuestas4.indexOf(respuestas4.get(indice * 3+2));
        indiceRespuestas4 = respuestas4.indexOf(respuestas4.get(indice * 3+3));
        indiceRespuestas5 = respuestas4.indexOf(respuestas4.get(indice * 3+4));
        indiceRespuestas6 = respuestas4.indexOf(respuestas4.get(indice * 3+5));
        indiceRespuestas7 = respuestas4.indexOf(respuestas4.get(indice * 3+6));
        indiceRespuestas8 = respuestas4.indexOf(respuestas4.get(indice * 3+7));
        indiceRespuestas9 = respuestas4.indexOf(respuestas4.get(indice * 3+8));
        indiceRespuestas10 = respuestas4.indexOf(respuestas4.get(indice * 3+9));
        indiceRespuestas11 = respuestas4.indexOf(respuestas4.get(indice * 3+10));
        indiceRespuestas12 = respuestas4.indexOf(respuestas4.get(indice * 3+11));
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rondaDePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rondaDePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rondaDePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rondaDePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rondaDePreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoPreg;
    private javax.swing.JPanel fondoResp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
